Homework1
made-ml-in-prod-2022/igor_itkin pull request #1
Opened 2022-05-09 16:43 UTC by YehudaItkin

Добрый день
Во первых - неожиданно оказалось, что я коммитил часть проекта с моего рабочего гита. Так случилось, но это тоже я

1. В описании к пулл реквесту описаны основные "архитектурные" и тактические решения, которые сделаны в вашей работе. В общем, описание того, что именно вы сделали и для чего, чтобы вашим ревьюерам было легче понять ваш код (1 балл)

2. В пулл-реквесте проведена самооценка, распишите по каждому пункту выполнен ли критерий или нет и на сколько баллов(частично или полностью) (1 балл)

3. Выполнено EDA, закоммитьте ноутбук в папку с ноутбуками (1 балл) Вы так же можете построить в ноутбуке прототип(если это вписывается в ваш стиль работы)**
Да, но там совсем простая моделька

4. Можете использовать не ноутбук, а скрипт, который сгенерит отчет, закоммитьте и скрипт и отчет (за это + 1 балл)
Не понял этот момент

5. Написана функция/класс для тренировки модели, вызов оформлен как утилита командной строки, записана в readme инструкцию по запуску (3 балла)
Да

6. Написана функция/класс predict (вызов оформлен как утилита командной строки), которая примет на вход артефакт/ы от обучения, тестовую выборку (без меток) и запишет предикт по заданному пути, инструкция по вызову записана в readme (3 балла)
Да

7. Проект имеет модульную структуру (2 балла)
Да

8. Использованы логгеры (2 балла)
Да

9. Написаны тесты на отдельные модули и на прогон обучения и predict (3 балла)
Нет

10. Для тестов генерируются синтетические данные, приближенные к реальным (2 балла)
можно посмотреть на библиотеки https://faker.readthedocs.io/, https://feature-forge.readthedocs.io/en/latest/
можно просто руками посоздавать данных, собственноручно написанными функциями.
Нет, не успел у сожалению

11. Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла)
Да

12. Используются датаклассы для сущностей из конфига, а не голые dict (2 балла)
Да, там где это было разумно. Точнее все написано на гидре

13. Напишите кастомный трансформер и протестируйте его (3 балла) https://towardsdatascience.com/pipelines-custom-transformers-in-scikit-learn-the-step-by-step-guide-with-python-code-4a7d9b068156
Вообще не понял, куда его присобачить 

14. В проекте зафиксированы все зависимости (1 балл)
Вроде да

15. Настроен CI для прогона тестов, линтера на основе github actions (3 балла). Пример с пары: https://github.com/demo-ml-cicd/ml-python-package
Да

PS: Можно использовать cookiecutter-data-science https://drivendata.github.io/cookiecutter-data-science/ , но поудаляйте папки, в которые вы не вносили изменения, чтобы не затруднять ревью

Дополнительные баллы=)

16. Используйте hydra для конфигурирования (https://hydra.cc/docs/intro/) - 3 балла
Да

17. Mlflow

разверните локально mlflow или на какой-нибудь виртуалке (1 балл)

залогируйте метрики (1 балл)

воспользуйтесь Model Registry для регистрации модели(1 балл) Приложите скриншот с вашим mlflow 

run DVC
выделите в своем проекте несколько entrypoints в виде консольных утилит (1 балл). Пример: https://github.com/made-ml-in-prod-2021/ml_project_example/blob/main/setup.py#L16 Но если у вас нет пакета, то можно и просто несколько скриптов

добавьте датасет под контроль версий (1 балл)

сделайте dvc пайплайн(связывающий запуск нескольких entrypoints) для изготовления модели(1 балл)

Для большего удовольствия в выполнении этих частей рекомендуется попробовать подключить удаленное S3 хранилище(например в Yandex Cloud, VK Cloud Solutions или Selectel)

2022-05-21 15:36 UTC, nickdndev requested changes

2022-05-21 15:36 UTC, nickdndev commented on src/model/trainer.py
> +            pipeline.append((name, value))
где используется PowerTransformer  в коде?

2022-05-30 08:51 UTC, YehudaItkin commented on src/model/trainer.py
> +            pipeline.append((name, value))
Видимо я непонятно написал в описании PR. Я не придумал где его использовать, поэтому сделал standalone, поскольку есть такое задание. Чисто теоретически его можно использовать для обогащения датасета, он будет работать из коробки

2022-05-30 09:04 UTC, YehudaItkin commented on src/model/trainer.py
> +            pipeline.append((name, value))
Пример использования я привел в отдельном ноутбуке

2022-05-30 17:25 UTC, nickdndev commented on src/model/trainer.py
> +            pipeline.append((name, value))
ок

2022-05-30 17:27 UTC, nickdndev approved these changes

2022-05-30 17:27 UTC, merged

2022-05-30 17:40 UTC, nickdndev commented
score :32